resolver: lts-19.1

packages:
  - 'external-stg-compiler'
  - 'external-stg'

extra-deps:
  - zip-1.7.2
  - souffle-haskell-3.3.0

# use GHC-WPC (whole program compiler)
compiler:       ghc-9.0.2.1000
compiler-check: match-exact
system-ghc:     true

nix:
  enable: false

# use local GHC (for development)
system-ghc: true
extra-path:
  - /home/doyougnu/programming/haskell/ghc-whole-program-compiler-project/ghc-wpc/_build/stage1/bin
